export const GET_PRODUCTS_START = 'GET_PRODUCTS_START'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL'

export const ADD_PRODUCTS_START = 'ADD_PRODUCTS_START'
export const ADD_PRODUCTS_SUCCESS = 'ADD_PRODUCTS_SUCCESS'
export const ADD_PRODUCTS_FAIL = 'ADD_PRODUCTS_FAIL'

export const EDIT_PRODUCTS_START = 'EDIT_PRODUCTS_START'
export const EDIT_PRODUCTS_SUCCESS = 'EDIT_PRODUCTS_SUCCESS'
export const EDIT_PRODUCTS_FAIL = 'EDIT_PRODUCTS_FAIL'

export const REMOVE_PRODUCTS_START = 'REMOVE_PRODUCTS_START'
export const REMOVE_PRODUCTS_SUCCESS = 'REMOVE_PRODUCTS_SUCCESS'
export const REMOVE_PRODUCTS_FAIL = 'REMOVE_PRODUCTS_FAIL'