export const GET_PRODUCTS_START = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS'
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS'
export const GET_PRODUCTS_LOGOUT = 'GET_PRODUCTS'

export const ADD_PRODUCTS_START = 'ADD_PRODUCTS'
export const ADD_PRODUCTS_SUCCESS = 'ADD_PRODUCTS'
export const ADD_PRODUCTS_FAIL = 'ADD_PRODUCTS'

export const EDIT_PRODUCTS_START = 'EDIT_PRODUCTS'
export const EDIT_PRODUCTS_SUCCESS = 'EDIT_PRODUCTS'
export const EDIT_PRODUCTS_FAIL = 'EDIT_PRODUCTS'

export const REMOVE_PRODUCTS_START = 'REMOVE_PRODUCTS'
export const REMOVE_PRODUCTS_SUCCESS = 'REMOVE_PRODUCTS'
export const REMOVE_PRODUCTS_FAIL = 'REMOVE_PRODUCTS'